package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsFeed<M extends BaseNewsFeed<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}

	public java.lang.Integer getAccountId() {
		return get("accountId");
	}

	public void setRefType(java.lang.Integer refType) {
		set("refType", refType);
	}

	public java.lang.Integer getRefType() {
		return get("refType");
	}

	public void setRefId(java.lang.Integer refId) {
		set("refId", refId);
	}

	public java.lang.Integer getRefId() {
		return get("refId");
	}

	public void setRefParentType(java.lang.Integer refParentType) {
		set("refParentType", refParentType);
	}

	public java.lang.Integer getRefParentType() {
		return get("refParentType");
	}

	public void setRefParentId(java.lang.Integer refParentId) {
		set("refParentId", refParentId);
	}

	public java.lang.Integer getRefParentId() {
		return get("refParentId");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("createAt");
	}

}
